---
version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - user-service
      - product-service
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks: [marketplace-network]
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports: [5432:5432]
    volumes: 
      - pgdata:/var/lib/postgresql/data 
      - ./db/init.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks: [marketplace-network]
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: barghest391@gmail.com
      PGADMIN_DEFAULT_PASSWORD: barghest
    ports: [5050:80]
    networks: [marketplace-network]
    depends_on: 
      postgres: 
        condition: service_healthy
    volumes:
        - ./db/servers.json:/pgadmin4/servers.json 
  user-service:
    build: ./user-service
    container_name: user-service
    depends_on: 
      postgres: 
        condition: service_healthy
    environment:
      PORT: 8081
      SERVER_HOST: localhost 
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: users
    ports: [8081:8081]
    networks: [marketplace-network]
  product-service:
    build: ./product-service
    container_name: product-service
    depends_on: 
      postgres: 
        condition: service_healthy 
    environment:
      PORT: 8082
      SERVER_HOST: localhost 
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: products
    ports: [8082:8082]
    networks: [marketplace-network]
  cart-service:
    build: ./cart-service
    container_name: cart-service
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      PORT: 8083
      SERVER_HOST: localhost 
      DB_HOST: postgres
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: barghest
      POSTGRES_DB: cart
    ports: [8083:8083]
    networks: [marketplace-network]   

networks:
  marketplace-network:
    driver: bridge
volumes:
  pgdata:
  pgadmin-data:

# kong:
  #   build: ./api-gateway 
  #   restart: always
  #   container_name: kong
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: postgres
  #     KONG_PG_USER: postgres
  #     KONG_PG_PASSWORD: barghest
  #     KONG_PROXY_ACCESS_LOG: "/dev/stdout"
  #     KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
  #     KONG_PROXY_ERROR_LOG: "/dev/stderr"
  #     KONG_ADMIN_ERROR_LOG: "/dev/stderr"
  #     KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  #     KONG_ADMIN_GUI_URL: "http://localhost:8002"
  #   depends_on: [postgres]
  #   ports:
  #     - "8000:8000"
  #     - "8001:8001"
  #     - "8002:8002"
  #   networks: [marketplace-network]
